### ISSUE TITLE
Please,Can you help me with the Spanish translation?

### ISSUE THREAD

**Issue by jayagon12** [edlynvillegas/evo-calendar#12]
I have configured spanish from evo-calendar.js
but it looks bad on Saturday and some months like for example January.

can it be fixed?

gracias
![foto](https://user-images.githubusercontent.com/65819474/82742303-9f440600-9d19-11ea-8880-1208a35203d9.png)

**Comment by edlynvillegas** [comment]
Hello @jayagon12 Sorry for the late reply. May I know if you did some modification in the js file? And also what date format are you using?

**Comment by koeve** [comment]
I have to set it up in Korean, too.
I modified the js file, but I get an error.
I'd like to use a cool Evo-calendar.

**Comment by edlynvillegas** [comment]
Hello @koeve! Thanks for using evocalendar :hugs: 
If you like, you can add korean version in the _dates_ object under **initials** variable in the js file :slightly_smiling_face:

**Comment by koeve** [comment]
Thank you so much.
Thanks to you, I was able to use this cool Evo-Calendar in Korean.
The context is weird using a translator. Please understand.
Thank you for your hard work.

**Comment by ClaudioRowe** [comment]
i'm having problems with spanish too, even when there is every date translated
![image](https://user-images.githubusercontent.com/60100296/84434115-6c48b000-abfd-11ea-8538-e4d1ecbb30eb.png)

**Comment by edlynvillegas** [comment]
Hello @ClaudioRowe sorry for the late reply, did you modify the code? Also check the date format you are using..

**Comment by ClaudioRowe** [comment]
I used it as it came and changing the language. I don't know what can it be, because spanish is in it by default, and i haven't make it work.

**Comment by edlynvillegas** [comment]
Hello @ClaudioRowe sorry for the late reply.. :sweat: I tried changing the language and It worked perfectly fine. I think there's a problem with the date format you are using.. or atleast try a different format.. Hope this will help you :+1:

**Comment by ClaudioRowe** [comment]
> Hello @ClaudioRowe sorry for the late reply.. 😓 I tried changing the language and It worked perfectly fine. I think there's a problem with the date format you are using.. or atleast try a different format.. Hope this will help you 👍

I've changed it to latam kind of date, can be it? there are some months that are shown as NaN

**Comment by edlynvillegas** [comment]
What latam kind of date? Can you provide an example so I can try it and see what's the problem :slightly_smiling_face:
