### ISSUE TITLE
Possibly add this as a npm package?

### ISSUE THREAD

**Issue by gjmolter** [edlynvillegas/evo-calendar#15]
I like to manage my front-end libs with `npm`. I think this project would benefit from being [published to npm](https://docs.npmjs.com/creating-and-publishing-unscoped-public-packages) or, at least, being added to a CDN, so it can be used quickly without us having to manually clone/download the source files.

Thanks for making this open-source, it saved me many hours of work! 👍

**Comment by edlynvillegas** [comment]
Tried to publish it to npm but forgot to include jquery as dependency :sweat_smile: as I'm new to publishing packages, but will try to work this out and will add to CDN also!

**Comment by edlynvillegas** [comment]
Hello again, @gjmolter! I successfully published **evo-calendar** as an npm package! Again, thanks for the suggestion :hugs:

**Comment by edlynvillegas** [comment]
Will close this now, @gjmolter thanks! :smile:
