### ISSUE TITLE
evo-calendar w/ front-end frameworks

### ISSUE THREAD

**Issue by DelRosarioEldrinRei** [edlynvillegas/evo-calendar#2]
Hi Edlyn Villegas,

I'm astonished by your great work.
I'm curious to ask if your calendar is supported
by front-end frameworks like react and angular?
Keep up the good work! 🥇 

Eldrin,

**Comment by edlynvillegas** [comment]
Hi, Eldrin!
Thank you for your appreciation!
And, of course! As long as you include jQuery in your project, you can use this plugin. 🙂
