### ISSUE TITLE
ReactJS: (R)EvoCalendar

### ISSUE THREAD

**Issue by gjmolter** [edlynvillegas/evo-calendar#22]
Hi Edlyn,

I've created a React component very much inspired by Evo Calendar, and I've called it [RevoCalendar](https://github.com/gjmolter/revo-calendar). Please take a look and I'd appreciate if you could link it on Evo's Readme for people using React.

Thanks!

**Comment by edlynvillegas** [comment]
Wow, you've done a wonderful job! I like using React too.
Already added on Readme :smile:
