### ISSUE TITLE
Event : selectEvent  | activeEvent.values not equal the selected event

### ISSUE THREAD

**Issue by joristackaert** [edlynvillegas/evo-calendar#24]
after using

$('#calendar').on('selectEvent', function (event, activeEvent) {
console.log(event.target);
console.log(activeEvent.description);
console.log(activeEvent.badge);
        });

It works fine if u have 1 event but when u have more then 1 event on the same day its values "description..." is always the same value of the first event in the eventlist and not the selected one (the second one). unless this is intentonal.

![image](https://user-images.githubusercontent.com/37837114/90750992-d8b6ee00-e2d5-11ea-9100-b6afa49bc387.png)

I can fix it by selecting the .target childnode childnode childnode description.data but it's a bit of work.

Regards 
Best calander ever btw.

**Comment by joristackaert** [comment]
nevermind i was a bit to fast. i uncommented your console.log in your code and i saw it's based on ID. and they had the same ID. making them show the same event. sorry how stupid of me. you can remove this issue.

**Comment by edlynvillegas** [comment]
Hi @joristackaert, thank you for the appreciation! :slightly_smiling_face:
