### ISSUE TITLE
Great Work! But..

### ISSUE THREAD

**Issue by realjimjim** [edlynvillegas/evo-calendar#3]
Hi Edlyn Villegas, I like your work very much! Clean UI and user friendly! I understand its beta version.. but I just want to confirm with you, is this work in iPhone? Because I tried it myself and view it with my iPhone, it will have some NaN value for the date and picking all day as today, but its ok and working in web version and android phone, it seems like its not compatible with iOS or safari i not sure.. 😅

Despite on the flaw, overall is very good, Keep it up!

Cheers! :D

**Comment by edlynvillegas** [comment]
Hello there, realjimjim! Thank you for the appreciation!
I haven't tried to test it in different browsers and platforms. :sweat_smile:
May I know what kind of project did you use this? Because I'm surprised this is actually being recognized :smile:

Thank you again!

**Comment by realjimjim** [comment]
> Hello there, realjimjim! Thank you for the appreciation!
> I haven't tried to test it in different browsers and platforms. 😅
> May I know what kind of project did you use this? Because I'm surprised this is actually being recognized 😄
> 
> Thank you again!

I use it in my dashboard project, which I think that event calendar is very useful in dashboard.
Plus there are no much event calendar that i can found in internet.. 😅

**Comment by edlynvillegas** [comment]
Goodluck with your project then! :grin: :blush:

**Comment by realjimjim** [comment]
You too Edlyn 😁

**Comment by realjimjim** [comment]
Hi Edlyn , I did some research about why it return NaN in iOS , and i found that it is because javascript `new Date()` return the format that iOS not desire.. you can refer these link to look out for a solution if you want to..

1. https://stackoverflow.com/questions/26657353/date-on-ios-device-returns-nan
2. https://neilsteventon.wordpress.com/2014/11/17/javascript-new-date-nan-on-iphone/

Good luck!

**Comment by edlynvillegas** [comment]
Hello realjimjim, thank you for these references, I will definitely try this solution with safari when I get time. 😁

Thank you!

**Comment by edlynvillegas** [comment]
Hello, since this issue, I rewrite the code to make it optimized and clean, and I also think it resolved the problem with safari.. you can see it for yourself :)

**Comment by realjimjim** [comment]
> Hello, since this issue, I rewrite the code to make it optimized and clean, and I also think it resolved the problem with safari.. you can see it for yourself :)

Great! Thanks for your commitment! :D
