### ISSUE TITLE
selectYear-trigger not working

### ISSUE THREAD

**Issue by debrouchee** [edlynvillegas/evo-calendar#34]
Hi, thanks for the nice plugin! 

During the integration I noticed that the event "selectYear" doesn't work.

**Comment by edlynvillegas** [comment]
Hello, thank you for the appreciation! :slightly_smiling_face: 

There's no **selectYear** event yet because I just thought no one will need it :sweat_smile: I'll add it.

**Comment by debrouchee** [comment]
Oh sorry, i mixed "events" and "methods"! I want to fetch events of the selected month by an api-call an add the results with the method "addCalendarEvent". This api-call should be executed if the year is changing. The event "selectYear" would be nice. ;-)

**Comment by edlynvillegas** [comment]
Hello, sorry for the late response. But the event **selectYear** has been added now! :hugs:
