### ISSUE TITLE
[Bug] Responsive

### ISSUE THREAD

**Issue by wahyupratama18** [edlynvillegas/evo-calendar#37]
Hi there, i'd really love your user interface. But, recently i found that on screen width around 770 and 900 when i'd open up both of the month and agenda column, the date table is overlayed to the right.

I hope that you could solved this. Thanks! :)
![image](https://user-images.githubusercontent.com/42894387/95015825-67f74580-0679-11eb-8dc3-88412abe2b92.png)

**Comment by joristackaert** [comment]
![image](https://user-images.githubusercontent.com/37837114/96982401-29d69e80-1520-11eb-8c04-c5f376db05fb.png)

Doing that fixed it for me. maybe give it a try ?

**Comment by wahyupratama18** [comment]
> ![image](https://user-images.githubusercontent.com/37837114/96982401-29d69e80-1520-11eb-8c04-c5f376db05fb.png)
> 
> Doing that fixed it for me. maybe give it a try ?

Thanks for your solution, i just tested it on the demo page and it's working. It would be nice i think if that is inserted to the cdn too 👍.
![image](https://user-images.githubusercontent.com/42894387/96985423-eba2a480-154a-11eb-8c79-ffb32a28712b.png)
