### ISSUE TITLE
Question: Is there a way to add a link to the event

### ISSUE THREAD

**Issue by aldunchev** [edlynvillegas/evo-calendar#49]
I have a dedicated pages for events and I would like to link to this page from the calendar or have a button with link. Is this possible or any way I can customise the look of the event to include a link?

Thanks in advance and thanks for the great plugin

**Comment by saber-mogaddas** [comment]
Hi
Add This Code To addEventList ::
`  if (event_data.link)
            markup += '<a href=' + event_data.link.url + ' class="event-link">' + event_data.link.label + '</a>';`
After Add AddeventList ::
` EvoCalendar.prototype.addEventList = function (event_data) {
        var _ = this, markup;
        var eventListEl = _.$elements.eventEl.find('.event-list');

        if (eventListEl.find('[data-event-index]').length === 0)
            eventListEl.empty();
        _.$active.events.push(event_data);
        markup = '<div class="event-container" role="button" data-event-index="' + (event_data.id) + '">';
        markup += '<div class="event-icon"><div class="event-bul ' + event_data.type + '"';
        if (event_data.color) {
            markup += 'style="background-color:' + event_data.color + '"'
        }
        markup += '></div></div><div class="event-info"><p class="event-title">' + _.limitTitle(event_data.name);
        if (event_data.badge)
            markup += '<span>' + event_data.badge + '</span>';
        markup += '</p>'
        if (event_data.description)
            markup += '<p class="event-desc">' + event_data.description + '</p>';

        if (event_data.link)
            markup += '<a href=' + event_data.link.url + ' class="event-link">' + event_data.link.label + '</a>';

        markup += '</div>';
        markup += '</div>';
        eventListEl.append(markup);

        _.$elements.eventEl.find('[data-event-index="' + (event_data.id) + '"]')
                .off('click.evocalendar')
                .on('click.evocalendar', _.selectEvent);
    }`

And Your event Data schema ::
`  var events = [{
            id: "1",
            name: "Event #3",
            description: "Lorem ipsum dolor sit amet.",
            date: "04/18/2021",
            type: "info",
            link:{
                label:"hi",
                url:"dasd"
            }
        }]`

**Comment by aldunchev** [comment]
Hey Saber, thanks for the help. For good or bad I went with another solution. However it would be nice if this goes into the library itself.

**Comment by SamirSalazar** [comment]
Do you mind sharing your solution?

**Comment by pkalexandr** [comment]
> 

Подскажите пожалуйста, у кого то сработало это решение? Никак не получается сделать ссылку на материал.

**Comment by SamirSalazar** [comment]
just put this <a href="https://example.com">Website</a> inside the
event description.
