### ISSUE TITLE
Changing first day of the week

### ISSUE THREAD

**Issue by IngridRegina** [edlynvillegas/evo-calendar#5]
Hey! Would be awesome if it would be possible to change the first day of the week to Monday.

**Comment by edlynvillegas** [comment]
Hello IngridRegina! Thank you for the feedback, really appreciate it. :hugs: 
I added a new setting called 'firstDayOfWeek', you can check and try it out!

**Comment by IngridRegina** [comment]
@edlynvillegas That's awesome! Thanks a bunch for the quick answer, didn't expect this feature to be added so fast!
