### ISSUE TITLE
Would it be possible to add multi-day events?

### ISSUE THREAD

**Issue by IngridRegina** [edlynvillegas/evo-calendar#6]
Hey! A possibility to add multi-day events would be great! Maybe it's possible to somehow pass an array as date, or add an end date in addition to start date.

**Comment by edlynvillegas** [comment]
Hello @IngridRegina :smile: 

This is a good suggestion! :+1:  I will try to do this as soon as the bugs were fixed.

Thank you for suggesting! :hugs:

**Comment by edlynvillegas** [comment]
Hello @IngridRegina, It took me too long to make this possible but now I've already added this feature! Hope this will still help you.
I will close this now. Again, thanks for suggesting this feature! :hugs:
