### ISSUE TITLE
Disable side bars on opening

### ISSUE THREAD

**Issue by 0x4A42** [edlynvillegas/evo-calendar#8]
Hi there,

I really love this calendar, so thanks for developing it! It's so lite and simple to configure, perfect for what I've been looking for!

Just curious if there's any way to disable the sidebars automatically opening upon page load. Currently, it will load with both the month picker and the note  section open, but I'm hoping for the note section to only open upon click and not by default.

Sorry if I missed it in the documentation! I saw there was the option to remove the buttons for toggling, but not to have them closed by default. 

Thanks in advance.

**Comment by edlynvillegas** [comment]
Hello @0x4A42, thank you for the appreciation :hugs: 

Also thank you for a good suggestions. I added a new settings called 'sidebarDisplayDefault' and 'eventDisplayDefault', you can check the documention. Feel free to write back if I missed your point. :smile: 

Goodluck with your project! :heart:
